import Head from "next/head";

import Footer from "@/components/footer";
import Annotations from "@/components/footer/Annotation";
import Navigation from "@/components/navigation";

export default function MainLayout({ children }) {
  return (
    <>
      <Head>
        <title>Site Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      {children}
      <Footer />
    </>
  );
}
